### ISSUE TITLE
Extract complex logic into individual functions and inline helper functions

### ISSUE THREAD

**Issue by NaC-L** [NaC-L/Mergen#28]
inline helper functions like div2 and idiv2  https://github.com/NaC-L/Mergen/blob/main/lifter/Semantics.cpp#L2454

and

extract inc and dec into seperate functions https://github.com/NaC-L/Mergen/blob/main/lifter/Semantics.cpp#L2890

**Comment by vxcall** [comment]
I'll work on it!

**Comment by vxcall** [comment]
been busy this week, but ill do it so bare with me please🙏🏻🙏🏻

**Comment by NaC-L** [comment]
Thank you @vxcall for your contributions to this issue!
